version: '3'

services:
  # Web server
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=itop
      - DB_USER=itop_user
      - DB_PASSWORD=itop_password
    volumes:
      - web_data:/var/www/html/itop

  # Database
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: itop
      MYSQL_USER: itop_user
      MYSQL_PASSWORD: itop_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  web_data:

# data stocker dans \\wsl$\docker-desktop-data\data\docker\volumes\itop_web_data\_data
# Command pour recuperer la data : docker run --rm --volumes-from itop-web-1 -v C:\Users\alanb\OneDrive\Documents\Docker\itop:/backup busybox tar cvf /backup/backup.tar /var/www/html/itop

# utile pour la suite : https://store.itophub.io/en_US/taxons/all-extensions